### ISSUE TITLE
ModemManager SMS module

### ISSUE THREAD

**Issue by cyrinux** [lasers/py3status#2]
Idk if lot of personne will use this, 
but i discover the SIM card I use for WWAN data have few SMS inside.
We can easyly read those with ModemManager, and based on new wwan module we can do something.
I see the module as a '[\?if=state SMS: {counter} [{last_sender}]]', which will be click-able to open a popup with last message for example.
I think there are programme for send sms from laptop, if it is not the case, i can do in parallele for excercise a small cli program which do this.
If we do this, must we read and ack/remove message, or simply use this as a read-only notifier?

Feel free to discuss about this.

You can see my few sms...

```
❯ busctl tree  org.freedesktop.ModemManager1 /org/freedesktop/ModemManager1/Modem
Service org.freedesktop.ModemManager1:
└─/org
  └─/org/freedesktop
    └─/org/freedesktop/ModemManager1
      ├─/org/freedesktop/ModemManager1/Bearer
      │ └─/org/freedesktop/ModemManager1/Bearer/5
      ├─/org/freedesktop/ModemManager1/Modem
      │ └─/org/freedesktop/ModemManager1/Modem/0
      ├─/org/freedesktop/ModemManager1/SIM
      │ └─/org/freedesktop/ModemManager1/SIM/0
      └─/org/freedesktop/ModemManager1/SMS
        ├─/org/freedesktop/ModemManager1/SMS/44
        ├─/org/freedesktop/ModemManager1/SMS/45
        ├─/org/freedesktop/ModemManager1/SMS/46
        ├─/org/freedesktop/ModemManager1/SMS/47
        ├─/org/freedesktop/ModemManager1/SMS/48
        ├─/org/freedesktop/ModemManager1/SMS/49
        ├─/org/freedesktop/ModemManager1/SMS/50
        ├─/org/freedesktop/ModemManager1/SMS/51
        ├─/org/freedesktop/ModemManager1/SMS/52
        ├─/org/freedesktop/ModemManager1/SMS/53
        ├─/org/freedesktop/ModemManager1/SMS/54
        ├─/org/freedesktop/ModemManager1/SMS/55
        ├─/org/freedesktop/ModemManager1/SMS/56
        ├─/org/freedesktop/ModemManager1/SMS/57
        ├─/org/freedesktop/ModemManager1/SMS/58
        ├─/org/freedesktop/ModemManager1/SMS/59
        ├─/org/freedesktop/ModemManager1/SMS/60
        ├─/org/freedesktop/ModemManager1/SMS/61
        ├─/org/freedesktop/ModemManager1/SMS/62
        ├─/org/freedesktop/ModemManager1/SMS/63
        ├─/org/freedesktop/ModemManager1/SMS/64
        └─/org/freedesktop/ModemManager1/SMS/65
Service /org/freedesktop/ModemManager1/Modem:
Failed to introspect object / of service /org/freedesktop/ModemManager1/Modem: Argument invalide
No objects discovered.

```

**Comment by lasers** [comment]
>which will be click-able to open a popup with last message for example.

Possibly with `self.py3.notify_user` (using notify-send + dunst/other) or expand the text across the bar... 

Not sure if it should be a new module or maybe a part of `wwan` module. Let's see how far you can get this to work... and see if it's useful. There is also `kdeconnector` module for Android phones that lets you read messages, do more.... Do you have Android phone? Check that out first. 

I think it'll be easier to just read messages. What you explain... I think users may not touch it because they would just use emails, their phones, or something else... Nothing to do with `py3status`. 

EDIT: At most, it would be useful to display number of new messages on your phone. No more.
EDIT: Going to bed now.

**Comment by cyrinux** [comment]
I will try to do something, you are right, maybe as a PR on wwan.

Yes I have android phone but I don't really like kde stuff based. I will
test (but it is another feature, here it is for read sms from Sim card
embedded in the laptop, not phone) .

I will try to do this and say you

**Comment by lasers** [comment]
We started working on this in #4.
